apiVersion: v1
kind: ConfigMap
metadata:
  name: ota-database-config
  namespace: vehicle-ota
data:
  MYSQL_DATABASE: vehicle_ota
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_NAME: vehicle_ota
  MONGO_HOST: mongodb
  MONGO_PORT: "27017"
  MONGO_DATABASE: vehicle_ota
