apiVersion: v1
kind: PersistentVolume
metadata:
  name: vehicle-ota-mysql-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vehicle-ota-nfs
  nfs:
    server: lab-nfs
    path: /srv/nfs/vehicle-ota/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: vehicle-ota
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vehicle-ota-nfs
  resources:
    requests:
      storage: 2Gi
